variables:
  CI_DESIGNATED_BRANCH: prpl/nightly
  CI_DESIGNATED_BRANCH_SLUG: prpl-nightly

include:
  - local: .gitlab/cdrouter.yml
  - local: .gitlab/cdrouter/wnc-freedom.yml
  - local: .gitlab/testbed.yml
  - local: .gitlab/testbed/wnc-freedom.yml

stages:
  - run

run test Freedom initramfs:
  extends: .wnc-freedom testbed
