variables:
  CI_DESIGNATED_BRANCH: prplos-next

include:
  - local: .gitlab/build.yml
  - local: .gitlab/cdrouter.yml
  - local: .gitlab/cdrouter/prpl-haze.yml
  - local: .gitlab/coverity.yml
  - local: .gitlab/testbed.yml
  - local: .gitlab/testbed/prpl-haze.yml

stages:
  - run
  - cdrouter

run test Haze initramfs:
  extends: .prpl-haze testbed
